import "../styles/globals.scss";
import React, { ReactNode } from "react";
import Head from "next/head"; // Note: next/head is not used in App Router, this will need to be replaced
import { Header, Footer } from "../components";
import { useMonitor, useHeadBlockInfo, useProducers, useSites } from "../hooks";
import Script from 'next/script'

// export const metadata = { // This is the new way to define metadata in App Router
//   title: "This is the default title",
//   description: "Generated by Next.js",
// };

type Props = {
  children?: ReactNode;
  title?: string; // Title will be handled by metadata or page-specific titles
  id?: string;
};

export default function RootLayout({ children, title = "This is the default title", id }: Props) {
  // preload data - This data fetching approach will likely need to change in App Router
  // useSites();
  // useHeadBlockInfo(false);
  // useProducers();
  // useMonitor(false);

  return (
    <html lang="en">
      {/*
        <head /> will contain the components returned by the nearest parent
        head.tsx. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
      */}
      {/* <Head>
        <title>{title}</title>
        <meta charSet="utf-8" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="shortcut icon" href="/favicon.ico" />
      </Head> */}
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <title>{title}</title> {}
      </head>
      <body id={id} className="relative mx-auto min-h-screen bg-slate-100 pb-32 text-slate-800 ">
        <Header />
        {children}
        <Footer />
        <Script id="google-analytics-script1" async src="https://www.googletagmanager.com/gtag/js?id=G-VH918P1NJQ"></Script>
        <Script
          id="google-analytics-script2"
          dangerouslySetInnerHTML={{
            __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-VH918P1NJQ');
          `,
          }}
        />
      </body>
    </html>
  );
}
